# Generated by Django 5.1.1 on 2024-10-09 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cronograma', '0002_cronograma_valor'),
        ('usuarioPadreFamilia', '0002_rename_user_name_usuariopadrefamilia_username_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cronograma',
            old_name='valor',
            new_name='valor_total',
        ),
        migrations.AddField(
            model_name='cronograma',
            name='estado_pago',
            field=models.CharField(default='PENDIENTE', max_length=20),
        ),
        migrations.AddField(
            model_name='cronograma',
            name='id_cronograma',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cronograma',
            name='usuario_padre',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='usuarioPadreFamilia.usuariopadrefamilia'),
        ),
        migrations.AlterField(
            model_name='cronograma',
            name='mes',
            field=models.CharField(max_length=20),
        ),
    ]
