# Generated by Django 5.1.1 on 2024-10-09 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cronograma', '0003_rename_valor_cronograma_valor_total_and_more'),
        ('descuento', '0002_descuento_id_descuento_and_more'),
        ('pago', '0004_pago_cronograma_pago_nombre_pago_pago_tipo_pago_and_more'),
        ('recibo', '0003_recibo_id_recibo_alter_recibo_codigo_barras_and_more'),
        ('usuarioPadreFamilia', '0002_rename_user_name_usuariopadrefamilia_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='cronograma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pagos_asociados_pago', to='cronograma.cronograma'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='descuentos',
            field=models.ManyToManyField(related_name='pagos_cronograma', to='descuento.descuento'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='estado_pago',
            field=models.CharField(default='PENDIENTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='pago',
            name='recibo',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pago_pago', to='recibo.recibo'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='tipo_pago',
            field=models.CharField(default='Pendiente', max_length=100),
        ),
        migrations.AlterField(
            model_name='pago',
            name='usuario_padre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pagos_asociados_pago', to='usuarioPadreFamilia.usuariopadrefamilia'),
        ),
    ]
